layout_spectrum: 0.8003513
typography_spectrum: 0.5901654
color:
  lightness: 0.7765958
  brandStrength: 0.31072
  saturation: 0.5106383
  rhythmicContrast: 0.4468313
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: 'otwmeruya '
